/*
 * @Author: hidari123
 * @Date: 2024-01-18 10:35:57
 * @LastEditors: hidari123
 * @LastEditTime: 2024-01-19 15:37:49
 * Copyright (c) 2024 by hidari, All Rights Reserved.
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
